require("src.loader")

-- base properties
require("src.animation.plant.peashooter.base")

-- parts
require("src.animation.plant.peashooter.parts.peashooter_leaf")
require("src.animation.plant.peashooter.parts.peashooter_stem")
require("src.animation.plant.peashooter.parts.peashooter_collar")
require("src.animation.plant.peashooter.parts.peashooter_head_leaf")
require("src.animation.plant.peashooter.parts.peashooter_head_leaf_stem")
require("src.animation.plant.peashooter.parts.peashooter_head_base")
require("src.animation.plant.peashooter.parts.custom_valentines")
require("src.animation.plant.peashooter.parts.custom_04")
require("src.animation.plant.peashooter.parts.custom_03")
require("src.animation.plant.peashooter.parts.custom_02")
require("src.animation.plant.peashooter.parts.custom_01")
require("src.animation.plant.peashooter.parts.custom_halloween")
require("src.animation.plant.peashooter.parts.custom_holiday")
require("src.animation.plant.peashooter.parts.custom_thingsandstuff")
require("src.animation.plant.peashooter.parts._custom")
require("src.animation.plant.peashooter.parts._peashooter_head")
require("src.animation.plant.peashooter.parts.peashooter_eye")
require("src.animation.plant.peashooter.parts.peashooter_mouth")
require("src.animation.plant.peashooter.parts.peashooter_lips")
require("src.animation.plant.peashooter.parts.gatlingpea_helmet_screw")
require("src.animation.plant.peashooter.parts.peashooter_stem_pea")
require("src.animation.plant.peashooter.parts.peashooter_lips_dimple")
require("src.animation.plant.peashooter.parts.peashooter_eye_lid")
require("src.animation.plant.peashooter.parts.peashooter_lips_closed")
require("src.animation.plant.peashooter.parts.peashooter_cheek")
require("src.animation.plant.peashooter.parts.peashooter_eye_lid_low")
require("src.animation.plant.peashooter.parts.peashooter_eye_closed")
require("src.animation.plant.peashooter.parts.peashooter_eye_closed_reverse")
require("src.animation.plant.peashooter.parts.peashooter_spit")
require("src.animation.plant.peashooter.parts.gatlingpea_helmet_back")
require("src.animation.plant.peashooter.parts.gatlingpea_eye_closed")
require("src.animation.plant.peashooter.parts.gatlingpea_helmet_strap_chin")
require("src.animation.plant.peashooter.parts.gatlingpea_helmet_strap")
require("src.animation.plant.peashooter.parts.gatlingpea_helmet_front")
require("src.animation.plant.peashooter.parts.gatlingpea_muzzle_blast")
require("src.animation.plant.peashooter.parts.gatlingpea_helemt_front_blast")
require("src.animation.plant.peashooter.parts.gatlingpea_eye")
require("src.animation.plant.peashooter.parts.gatlingpea_eye_lid")
require("src.animation.plant.peashooter.parts.gatlingpea_eye_lid_low")

-- test
require("src.animation.plant.peashooter.test")
