require("src.loader")

require("src.animations.plant.cold_snapdragon.base")

require("src.animations.plant.cold_snapdragon.parts.custom_02")
require("src.animations.plant.cold_snapdragon.parts.custom_01")
require("src.animations.plant.cold_snapdragon.parts._custom")
require("src.animations.plant.cold_snapdragon.parts.snowpea_frostpuff_anim")
require("src.animations.plant.cold_snapdragon.parts.bounding_box copy 2")
require("src.animations.plant.cold_snapdragon.parts._iceberg_frostball copy")
require("src.animations.plant.cold_snapdragon.parts.explode puff copy 5")
require("src.animations.plant.cold_snapdragon.parts.coconut_explosion_01 copy 5")
require("src.animations.plant.cold_snapdragon.parts.melonpult_cloud_front copy 5")
require("src.animations.plant.cold_snapdragon.parts.melonpult_body copy 4")
require("src.animations.plant.cold_snapdragon.parts.whiteMelonBody copy 4")
require("src.animations.plant.cold_snapdragon.parts.iceberg_white copy")
require("src.animations.plant.cold_snapdragon.parts.iceberg copy")
require("src.animations.plant.cold_snapdragon.parts.iceberg_sparkle")

require("src.animations.plant.cold_snapdragon.animations.idle")
require("src.animations.plant.cold_snapdragon.animations.idle2")
require("src.animations.plant.cold_snapdragon.animations.idle3")
require("src.animations.plant.cold_snapdragon.animations.attack")
require("src.animations.plant.cold_snapdragon.animations.plantfood")
require("src.animations.plant.cold_snapdragon.animations.water")
